name: Deploy Vite App to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v2
        with:
          publish-dir: ./dist
